"""add_sharing_fields_to_recipes

Revision ID: 0d3074f3dd7b
Revises: df3304457245
Create Date: 2025-11-12 21:34:06.779414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d3074f3dd7b'
down_revision: Union[str, Sequence[str], None] = 'df3304457245'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('is_public', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('recipes', sa.Column('share_token', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_recipes_share_token'), 'recipes', ['share_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recipes_share_token'), table_name='recipes')
    op.drop_column('recipes', 'share_token')
    op.drop_column('recipes', 'is_public')
    # ### end Alembic commands ###
