"""Add rating field to recipes

Revision ID: 8c4bd0ffcfc2
Revises: 6dee10f05917
Create Date: 2025-11-11 18:34:05.566296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c4bd0ffcfc2'
down_revision: Union[str, Sequence[str], None] = '6dee10f05917'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('rating', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'rating')
    # ### end Alembic commands ###
