"""add_nutritional_information_to_recipes

Revision ID: c74f42b48abc
Revises: 8c4bd0ffcfc2
Create Date: 2025-11-12 20:58:04.407365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c74f42b48abc'
down_revision: Union[str, Sequence[str], None] = '8c4bd0ffcfc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('calories', sa.Integer(), nullable=True))
    op.add_column('recipes', sa.Column('protein', sa.Float(), nullable=True))
    op.add_column('recipes', sa.Column('carbohydrates', sa.Float(), nullable=True))
    op.add_column('recipes', sa.Column('fat', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'fat')
    op.drop_column('recipes', 'carbohydrates')
    op.drop_column('recipes', 'protein')
    op.drop_column('recipes', 'calories')
    # ### end Alembic commands ###
